version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
  server:
    build:
      context: .
      dockerfile: ./docker-files/server/Dockerfile
    command: python ./map-app/server/manage.py runserver 0.0.0.0:3001
    volumes:
      - .:/code
    restart: always
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - db
  
  client:
    build:
      context: .
      dockerfile: ./docker-files/client/Dockerfile
    command: npm start
    working_dir: /code/map-app/client/
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server