# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlocationtime',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
